DROP TABLE COMMENTS CASCADE CONSTRAINTS ;
DROP TABLE POST CASCADE CONSTRAINTS ;
DROP TABLE CATEGORY CASCADE CONSTRAINTS ;
DROP TABLE BLOG CASCADE CONSTRAINTS ;
DROP TABLE MEMBER CASCADE CONSTRAINTS ;
DROP SEQUENCE POST_SEQ;	
DROP SEQUENCE COMMENTS_SEQ;	
DROP SEQUENCE CATEGORY_SEQ;	


CREATE TABLE MEMBER (
  ID          VARCHAR2(10)		NOT NULL,
  PASSWORD    VARCHAR2(20)		NOT NULL, 
  NAME        VARCHAR2(50)		NOT NULL,
  ROLE        VARCHAR2(32)		NOT NULL,
  REG_DATE 	  DATE,
  PRIMARY KEY ( ID ) 
);   

CREATE TABLE BLOG
(
ID 		VARCHAR2(10) NOT NULL ,
TITLE	VARCHAR2(100) NOT NULL,
STATUS	VARCHAR2(10),
TAGS     VARCHAR2 (500),
CONSTRAINT PK_BLOG PRIMARY KEY (ID),
CONSTRAINT FK_BLOG_ID FOREIGN KEY (ID) REFERENCES MEMBER(ID) ON DELETE CASCADE 
);


CREATE TABLE CATEGORY
(
NO NUMBER(20) NOT NULL ,
NAME VARCHAR2(500) NOT NULL ,
DESCRIPTION VARCHAR2(1000) ,
REG_DATE DATE,
BLOG_ID VARCHAR2(10) NOT NULL ,
CONSTRAINT PK_CATEGORY PRIMARY KEY (NO),
CONSTRAINT FK_CATEGORY_BLOG_ID FOREIGN KEY (BLOG_ID) REFERENCES BLOG(ID) ON DELETE CASCADE 
);


CREATE TABLE POST
(
NO NUMBER(20) NOT NULL,
TITLE   VARCHAR2(500) NOT NULL,
CONTENT VARCHAR2(4000),
REG_DATE DATE,
CATEGORY_NO NUMBER(20) NOT NULL ,
CONSTRAINT PK_POST PRIMARY KEY (NO),
CONSTRAINT FK_POST_CATEGORY_NO  FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(NO) ON DELETE CASCADE 
);


CREATE TABLE COMMENTS
(
NO NUMBER(20) NOT NULL,
CONTENT VARCHAR2(1000) NOT NULL,
POST_NO NUMBER(20) NOT NULL,
MEMBER_ID VARCHAR2(10) NOT NULL,
REG_DATE DATE,
CONSTRAINT PK_COMMENTS PRIMARY KEY (NO),
CONSTRAINT FK_COMMENTS_POST_NO FOREIGN KEY(POST_NO) REFERENCES POST(NO) ON DELETE CASCADE,
CONSTRAINT FK_COMMENTS_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE
);


CREATE SEQUENCE POST_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999
NOCACHE
NOCYCLE;

CREATE SEQUENCE COMMENTS_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999
NOCACHE
NOCYCLE;

CREATE SEQUENCE CATEGORY_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999
NOCACHE
NOCYCLE;

INSERT INTO MEMBER(ID, PASSWORD, NAME, ROLE, REG_DATE) VALUES('admin','admin','관리자', 'ADMIN', SYSDATE);
COMMIT;
